server:
  port: 8082 # Puerto diferente al de Auth (8081)

spring:
  application:
    name: room-service

  datasource:
    # Nota el puerto 5432 y el nombre de DB diferente para aislamiento total
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:roomDB}
    username: ${DB_USER:room}
    password: ${DB_PASSWORD:room123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' es apto para desarrollo, considerar 'validate' para entornos productivos
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

# Configuración necesaria para validar los tokens emitidos por Auth-Service
jwt:
  # Debe ser la misma clave que en auth-service
  secret: ${JWT_SECRET:mi_clave_secreta_super_segura_de_maestria_2026}
  expiration: 3600000