server:
  port: 8082

spring:
  application:
    name: room-service

  datasource:
    # Añadidos los valores por defecto para evitar el Crash
    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:breaze_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

app:
  # Aseguramos que la auditoría apunte a tu Lambda si la variable falla
  auditoria-url: ${AUDITORIA_URL:https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits}