apiVersion: v1
kind: Secret
metadata:
  name: secret-auth
  namespace: breaze
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASSWORD: admin123
  DB_NAME: authdb
  JWT_SECRET: 9fK3xP8vL2qZr7TnW5yB1sD4mH6uJ0aC
  INTERNAL_SHARED_SECRET: breaze-internal
  AUDITORIA_URL: http://api-gateway/internal/audits