apiVersion: v1
kind: Secret
metadata:
  name: secret-booking
  namespace: breaze
type: Opaque
stringData:
  DB_USER: appuser
  DB_PASSWORD: admin123
  DB_NAME: bookingdb
  INTERNAL_SHARED_SECRET: breaze-internal
  ROOM_SERVICE_URL: http://room-service
  AUDITORIA_URL: http://api-gateway/internal/audits
