apiVersion: v1
kind: Secret
metadata:
  name: secret-gateway
  namespace: breaze
type: Opaque
stringData:
  JWT_SECRET: supersecretojwt
  AUDITORIA_LAMBDA_URL: https://example.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits

