apiVersion: v1
kind: Secret
metadata:
  name: secret-gateway
  namespace: breaze
type: Opaque
stringData:
  JWT_SECRET: 9fK3xP8vL2qZr7TnW5yB1sD4mH6uJ0aC
  INTERNAL_SHARED_SECRET: breaze-internal
  AUDITORIA_LAMBDA_BASE_URL: https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com
  AUDITORIA_LAMBDA_PATH: /default/breaze_in_the_moon_audits