apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: breaze
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          image: api-gateway:latest
          ports:
            - containerPort: 8080
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-gateway
                  key: JWT_SECRET
            - name: INTERNAL_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  name: secret-gateway
                  key: INTERNAL_SHARED_SECRET
            - name: AUDITORIA_LAMBDA_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: secret-gateway
                  key: AUDITORIA_LAMBDA_BASE_URL
            - name: AUDITORIA_LAMBDA_PATH
              valueFrom:
                secretKeyRef:
                  name: secret-gateway
                  key: AUDITORIA_LAMBDA_PATH
            - name: AUTH_SERVICE_URL
              value: http://auth-service:8081
            - name: ROOM_SERVICE_URL
              value: http://room-service:8082
            - name: BOOKING_SERVICE_URL
              value: http://booking-service:8083
