services:
  # 1. FRONTEND: Tu aplicación React
  frontend:
    build:
      context: ./breaze-frontend
    container_name: breaze-frontend-c
    ports:
      - "8080:80"
    networks:
      - breaze-net
    depends_on:
      - api-gateway

  # 2. API GATEWAY: El "portero" que recibe las llamadas del Frontend (puerto 8081)
  api-gateway:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: api-gateway
    container_name: breaze-api-gateway
    ports:
      - "8081:8080"
    environment:
      # Configuramos la auditoría también aquí por si el Gateway genera eventos
      - APP_AUDITORIA-URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    networks:
      - breaze-net

  # 3. AUTH-SERVICE: Donde está el código de EventPublisherAdapter
  auth-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: auth-service
    container_name: breaze-auth-service
    environment:
      # Conexión vital a tu Lambda de AWS
      - APP_AUDITORIA-URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    networks:
      - breaze-net

  # 4. ROOM-SERVICE: Gestión de habitaciones
  room-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: room-service
    container_name: breaze-room-service
    environment:
      - APP_AUDITORIA-URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    networks:
      - breaze-net

  # 5. BOOKING-SERVICE: Gestión de reservas
  booking-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: booking-service
    container_name: breaze-booking-service
    environment:
      - APP_AUDITORIA-URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    networks:
      - breaze-net

networks:
  breaze-net:
    driver: bridge