services:
  # --- LA BASE DE DATOS (Vital para que el resto funcione) ---
  postgres-db:
    image: postgres:15
    container_name: breaze-db
    environment:
      - POSTGRES_DB=breaze_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - breaze-net

  # --- FRONTEND ---
  frontend:
    build:
      context: ./breaze-frontend
    container_name: breaze-frontend-c
    ports:
      - "8080:80"
    networks:
      - breaze-net
    depends_on:
      - api-gateway

  # --- API GATEWAY ---
  api-gateway:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: api-gateway
    container_name: breaze-api-gateway
    ports:
      - "8081:8080"
    networks:
      - breaze-net

  # --- AUTH-SERVICE (Microservicio de Autenticación) ---
  auth-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: auth-service
    container_name: breaze-auth-service
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=breaze_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - JWT_SECRET=mi_clave_secreta_123456
      - AUDITORIA_URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    depends_on:
      - postgres-db
    networks:
      - breaze-net

  # --- ROOM-SERVICE (Donde creas las habitaciones) ---
  room-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: room-service
    container_name: breaze-room-service
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=breaze_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AUDITORIA_URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    depends_on:
      - postgres-db
    networks:
      - breaze-net

  # --- BOOKING-SERVICE (Reservas) ---
  booking-service:
    build:
      context: ./breaze-backend
      args:
        MODULE_NAME: booking-service
    container_name: breaze-booking-service
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=breaze_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - AUDITORIA_URL=https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits
    depends_on:
      - postgres-db
    networks:
      - breaze-net

networks:
  breaze-net:
    driver: bridge