server:
  port: 8083 # Cada micro tendrá su puerto (8081 Auth, 8082 Rooms, 8083 Booking)

spring:
  application:
    name: booking-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:bookingDB}
    username: ${DB_USER:booking}
    password: ${DB_PASSWORD:booking123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# Configuración personalizada para tu JwtService
jwt:
  secret: ${JWT_SECRET:mi_clave_secreta_super_segura_de_maestria_2026}
  expiration: 3600000 # 1 hora en milisegundos