server:
  port: 8081 # Cada micro tendrá su puerto (8081 Auth, 8082 Rooms, 8083 Booking)

spring:
  application:
    name: auth-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service API
        url: /openapi/auth-service.yml

# Configuración personalizada para tu JwtService
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000 # 1 hora en milisegundos

app:
  auditoria-url: ${AUDITORIA_URL}

internal:
  shared-secret: ${INTERNAL_SHARED_SECRET}
