server:
  port: 8081

spring:
  application:
    name: auth-service
  jackson:
    serialization:
      write-dates-as-timestamps: false

  datasource:
    # Agregamos :localhost, :5432, etc. como salvavidas
    url: jdbc:postgresql://${DB_HOST:postgres-db}:${DB_PORT:5432}/${DB_NAME:auth_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service API
        url: /openapi/auth-service.yml

jwt:
  secret: ${JWT_SECRET:mi_clave_secreta_super_segura_123456}
  expiration: 3600000 

app:
  # Cambiamos a APP_AUDITORIA_URL para que coincida con Docker
  auditoria-url: ${APP_AUDITORIA_URL:https://0m1tpn7om6.execute-api.us-east-1.amazonaws.com/default/breaze_in_the_moon_audits}