server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        # Microservicio de Autenticación
        - id: auth-service
          uri: http://localhost:8081 # URL directa del micro de Auth
          predicates:
            - Path=/auth/**

        # Microservicio de Habitaciones (Room Service)
        - id: room-service
          uri: http://localhost:8082 # URL directa del micro de Rooms
          predicates:
            - Path=/api/v1/rooms/**

        # Microservicio de Reservas (Booking Service)
        - id: booking-service
          uri: http://localhost:8083 # URL directa del micro de Bookings
          predicates:
            - Path=/api/v1/bookings/**

      # Configuración de CORS centralizada (Vital si vas a conectar un Frontend o App)
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
            allowedHeaders: "*"

jwt:
  secret: ${JWT_SECRET:mi_clave_secreta_super_segura_de_maestria_2026}
  expiration: 3600000 # 1 hora en milisegundos